# Schema for the Better Exposed Filters configuration files.
views.exposed_form:
  type: views_exposed_form
  label: 'Better Exposed Filters'
  mapping:
    bef.*:
      label: 'BEF filter settings'
      type: mapping
      mapping:
        bef_format:
          type: string
          label: 'Display exposed filter as'
        more_options:
          type: mapping
          mapping:
            bef_select_all_none:
              type: boolean
              label: 'Add select all/none links'
            bef_select_all_none_nested:
              type: boolean
              label: 'Add select all/none links for heirarchical filters'
            bef_collapsible:
              type: boolean
              label: 'Place filter in a collapsible HTML element'
            is_secondary:
              type: boolean
              label: 'This filter is a secondary option'
            rewrite:
              type: mapping
              mapping:
                filter_rewrite_values:
                  type: text
                  label: 'Rewrite filter options'
        slider_options:
          type: mapping
          mapping:
            bef_slider_min:
              type: integer
              label: 'Silder min option'
            bef_slider_max:
              type: integer
              label: 'Silder max option'
            bef_slider_step:
              type: integer
              label: 'Silder step option'
            bef_slider_animate:
              type: integer
              label: 'Silder animate option'
            bef_slider_orientation:
              type: string
              label: 'Silder orientation'
    bef.general:
      label: 'General BEF settings'
      type: mapping
      mapping:
        allow_secondary:
          type: boolean
          label: 'Enable secondary exposed form options'
        secondary_label:
          type: label
          label: 'Secondary options label'
        autosubmit:
          type: boolean
          label: 'Autosubmit'
        autosubmit_hide:
          type: boolean
          label: 'Hide submit button'
    bef.sort:
      label: 'Exposed sort BEF settings'
      type: mapping
      mapping:
        bef_format:
          type: string
          label: 'Display exposed sort options as'
        advanced:
          type: mapping
          mapping:
            collapsible:
              type: boolean
              label: 'Make sort options collapsible'
            collapsible_label:
              type: label
              label: 'Collapsible details element title'
            combine:
              type: boolean
              label: 'Combine sort order with sort by'
            combine_rewrite:
              type: text
              label: 'Rewrite combined sort options'
            reset:
              type: boolean
              label: 'Include reset sort option'
            reset_label:
              type: label
              label: 'Reset sort label'
            is_secondary:
              type: boolean
              label: 'Sort is a secondary option'
